### ISSUE TITLE
Investigate why we depend on OpenSSL

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#105]
Apparently, depending on testcontainers brings in a dependency on openssl. That shouldn't be the case because we don't do any networks requests (yet).

Investigate and fix.

**Comment by D4nte** [comment]
It's due to web3 and to bitcoin_rpc_client that brings in json_client (that brings in tls)

**Comment by thomaseizinger** [comment]
Interesting! Those should be devDependencies I think and hence should not
affect downstream users.

**Comment by D4nte** [comment]
Yep, actually it does not :) see comit-network/comit-rs#1376

**Comment by thomaseizinger** [comment]
Closing then :)
