### ISSUE TITLE
No container teardown for isolated test

### ISSUE THREAD

**Issue by luckysori** [testcontainers/testcontainers-rs#106]
The expectation is that `testcontainers` should tear down a container after a test is completed, but when running the following test in isolation using `cargo test <TESTNAME>`

```rust
    #[test]
    fn test() {
        let docker = testcontainers::clients::Cli::default();
        docker.run(testcontainers::images::coblox_bitcoincore::BitcoinCore::default());
    }
```
the docker container remains up after the test has passed.

Interestingly, this doesn't happen if the test is run using `cargo test`.

**Comment by thomaseizinger** [comment]
Any chance you can try to reproduce the issue with latest `dev` @luckysori?

**Comment by luckysori** [comment]
The original issue was about containers staying up when running tests independently, but I just ran `cargo test` on `comit-network/thor` after updating the `testcontainers-rs` dependency to `dev` and 5 containers have stayed up.

**Comment by luckysori** [comment]
> The original issue was about containers staying up when running tests independently, but I just ran `cargo test` on `comit-network/thor` after updating the `testcontainers-rs` dependency to `dev` and 5 containers have stayed up.

Actually, I think the reason this happened was unrelated to `testcontainers-rs`! Having tried it some more, it seems like containers are being torn down correctly. I am happy to close this issue and keep and report back if I notice anything like this again.
