### ISSUE TITLE
Pin rust version in `rust-toolchain` file to MSRV

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#119]
## Problem

Currently, our `rust-toolchain` file says `stable`.
This can cause your CI to fail because `stable` is a moving target and components like rustfmt might have different opinions about how code should be formatted for different versions.

## Goal

1. Have a stable CI
2. State a MSRV (minimum supported rust version) for other users

## Recommendation

Figure out what the MSRV for our project is an pin it to that.

**Comment by D4nte** [comment]
The easiest way to "figure it out" is just select it arbitrarily :)
