### ISSUE TITLE
Debugging Travis Build Breaking

### ISSUE THREAD

**Issue by 4meta5** [testcontainers/testcontainers-rs#140]
I can't make sense of why the build in https://github.com/testcontainers/testcontainers-rs/pull/139 is breaking. Here is the first error when `cargo build` is run:

```rust
$ cargo build

    Updating crates.io index

   Compiling smallvec v1.0.0

   Compiling percent-encoding v2.1.0

error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)

  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:38:1

   |

38 | extern crate alloc;

   | ^^^^^^^^^^^^^^^^^^^
...
```

Note that this branch compiles and all tests passed when `cargo build` and `cargo test` are run on my local machine

**Comment by D4nte** [comment]
This is most likely due to the difference of rust version used.
The `rust-toolchain` file contains `stable`

We can see in the CI:
```
$ curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION --profile=minimal -y
...
$ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)
$ rustup --version
rustup 1.20.2 (13979c968 2019-10-16)
$ cargo --version
cargo 1.32.0 (8610973aa 2019-01-02)
```

So it looks like Travis is installing an older version of Rust. Latest stable being 1.39.0.

Let me delete Travis cache and see if it helps.

**Comment by D4nte** [comment]
@thomaseizinger do you know why travis is running two builds? one for 1.32.0 and one for 1.36.0? 

https://travis-ci.org/testcontainers/testcontainers-rs/builds/622306051?utm_source=github_status&utm_medium=notification

**Comment by 4meta5** [comment]
added a commit to #139 -- this can be closed once/if that PR is merged

**Comment by thomaseizinger** [comment]
> The current (undocumented) MSRV (Minimal Supported Rust Version) is 1.32.0:
> 
> https://github.com/testcontainers/testcontainers-rs/blob/b6f9dbe82478f28f5c5b46686bcc4dfe422fd9ea/.travis.yml#L4
> 
> From my point of view, it is if fine to change it to 1.36.0 (current stable is 1.39.0) so feel free to do a update to update the Travis config.

Yes it is fine to change that :)
The reason it is there is so that we know, when the MSRV changes!

**Comment by thomaseizinger** [comment]
This is fixed.
