### ISSUE TITLE
Provide an async API

### ISSUE THREAD

**Issue by wngr** [testcontainers/testcontainers-rs#142]
Following the discussion in https://github.com/testcontainers/testcontainers-rs/pull/141#issuecomment-569583808, it would be nice to provide an additional async API (or replace the existing one?). This would allow an easier integration with libraries like https://github.com/softprops/shiplift or https://github.com/fussybeaver/bollard to ease future introduction of additional features into this library.

Opening this issue to initiate a discussion.

**Comment by thomaseizinger** [comment]
Totally up for it!

Initial thoughts:

- prefer async over blocking to allow native integration
- can use `async_trait` to make our traits `async` fn
- things like `#[tokio::test]` and `#[async_std::test]` should make it trivial to use `await` in a test context, hence it should hurt to not provide a blocking API.

**Comment by thomaseizinger** [comment]
Thinking about this, I am not sure if we can realize the current functionality in async because there isn't an async-drop yet.
Hence, at least for that we would need a synchronous API so the containers get cleaned up properly.

**Comment by thomaseizinger** [comment]
An initial implementation has been merged with https://github.com/testcontainers/testcontainers-rs/pull/268.

It does still have some bugs so it is going to be a while until it can actually be released.

That said, I also opened https://github.com/testcontainers/testcontainers-rs/issues/273 to track the implementation of the async interface on the existing CLI client.
