### ISSUE TITLE
Rethink usage pattern

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#16]
At the moment, you have to import two crates in order to use an image.

- `testcontainers`
- the image crate itself

This can lead to problems when the versions of the transitive dependency on `testcontainers` in the image crate doesn't match the one you are depending on explicitly.

There are several ways on how to proceed with this:

1. Introduce a method `start` / `run` / `deploy` on the `Image` trait that uses testcontainers under the hood to start the image. This way, you don't have to depend on testcontainers in the user code.
2. Re-export `testcontainers` from every image so that one can import from the transitive dependency.
3. Merge all crates into one. The downside would be that users can then no longer selectively depend on things and I am not sure, if this adds any disadvantages regarding compile-time or binary size. Actually, since `testcontainers` is always a test-dependency, this would be secondary issue.

**Comment by thomaseizinger** [comment]
A problem with solution 1 is that in order for it to make sense, it have to be implemented on the `Image` trait like this:

```rust
pub trait Image
where
    Self: Sized + Default,
    Self::Args: IntoIterator<Item = String>,
{
    type Args;

    fn start(self) -> Container<DockerCli, Self> {
        let docker = DockerCli::new();

        docker.run(self)
    }

    ...
}
```

1. This forces the usage of a specific Docker client (not nice but would be ok)
2. In order to use methods from a trait, the trait needs to be in scope. Here we are back again with a necessary import from `testcontainers`.

**Comment by LLFourn** [comment]
I might be thick but I don't really get the issue. Can't the image crate just compile with whatever testcontainers version you're using assuming the minor versions are the same?

**Comment by thomaseizinger** [comment]
It needs to be the exact same version actually: Cargo needs to be able to find a match between the semver range of the testcontainers dependency for the image crate as well as the one that the user code depends on which tries to start the image.

If the two don't match, the code will not compile because the stuff you import directly from `testcontainers` is different from what the image crate gets compiled against.

**Comment by LLFourn** [comment]
So if we change the dependency on things to something like:
```
[dependencies]
testcontainers = { path = "../../testcontainers", version = "0.2" }
```
for the images. And a user uses testcontainers version "0.2.2" then it won't just work? Why would it not compile the image against 0.2.2 then as well?

**Comment by D4nte** [comment]
You cannot use path in combination with version

**Comment by thomaseizinger** [comment]
You can, cargo will use the version upon publishing and the path for local development.
