### ISSUE TITLE
Increase sleep period when waiting for logs to be ready

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#17]
At the moment we wait for 100ms for the logs to be ready. Apparently, this is not enough as the tests on || keep failing randomly.

https://github.com/coblox/testcontainers-rs/blob/814ee6da67c6231990aa09070b6790100f848378/testcontainers/src/docker_cli.rs#L50-L68

Increasing the timeout to something like 500ms should not hurt that much because the container starts up in the meantime anyway. It is basically just a matter of where we spend the time waiting: In the loop that polls the logs or in the sleep before that.

**Comment by D4nte** [comment]
@thomaseizinger to check if done

**Comment by thomaseizinger** [comment]
Done in https://github.com/testcontainers/testcontainers-rs/commit/b6eed5d920f10d4637186aaebcc7384f68f5685e.
