### ISSUE TITLE
[Question] Running Testcontainers in Github Actions

### ISSUE THREAD

**Issue by Geigerkind** [testcontainers/testcontainers-rs#175]
Hi there!
Im not sure if this is the right place to ask these specific questions, but I just can't figure out how to solve this, trying to get this running since days.

So Im trying to get my Integration tests to run in the CI using Github Actions. Before I started a docker container manually and executed tests in the container, doing the cleanup manually. With Testcontainers this is no longer required but the containers need to be able to be started.

So locally everything works fine.

The CI however spits out an interesting failure message that I cant make sense of:
https://github.com/Geigerkind/LegacyPlayersV3/runs/777848531
(Scroll down to line 651) "Cannot run dynamic test fn out-of-process"

The testcotainer is a GenericImage, downloading a MariadDB and linking a volume.
https://github.com/Geigerkind/LegacyPlayersV3/blob/dev/Backend/src/tests/test_container.rs

A container is then started in each integration test function, e.g.
https://github.com/Geigerkind/LegacyPlayersV3/blob/dev/Backend/src/modules/account/tests/get.rs

Does anyone have an idea how I can fix this?

Cheers!

**Comment by thomaseizinger** [comment]
Interesting, I have not encountered that so far.

We are running tests based on testcontainers in GitHub actions CI just fine: https://github.com/comit-network/comit-rs/runs/777309093?check_suite_focus=true#step:9:216

I traced the error you are getting to this line inside the Rust source code:

https://github.com/rust-lang/rust/blob/e8ff4bcbd02475cf487cd101bf32954dc63366d4/src/libtest/lib.rs#L496

Looking where `RunStrategy` gets set, we arrive here:

https://github.com/rust-lang/rust/blob/e8ff4bcbd02475cf487cd101bf32954dc63366d4/src/libtest/lib.rs#L252-L256

You are setting `panic_abort` in your CI here:

https://github.com/Geigerkind/LegacyPlayersV3/blob/c334cefee289754c0e6a836a1c01e05270fdf054/.github/workflows/CI.yml#L31

Seems like you need to also set `force_run_in_process` to make sure the correct `RunStrategy` gets chosen :)

Hopefully that helps!

**Comment by Geigerkind** [comment]
Hey thomaseizinger,
thanks for the fast answer :)

I tried it here: https://github.com/Geigerkind/LegacyPlayersV3/runs/779513961?check_suite_focus=true#step:4:693
At least the failure message is different.

I also tried looking into how the comit-rs project is firing up the container in the test, 
but I cant seem to make out where the container startup was defined.
(And I learned about actions/cache and how to mock in Rust :O, Nice)
https://github.com/comit-network/comit-rs/blob/dev/comit/tests/ethereum_go_back_into_the_past.rs

I also noticed that this is an `tokio::test`. As I have never worked with tokio, I dont know if this works differently.

**Comment by thomaseizinger** [comment]
Hehe, glad you got it sorted and could learn something in the process :)

You might need panic=abort for the code coverage you are trying to do in your CI. Not quite sure but I've seen those flags be used in the past together with CI.

The code snippet from libtest I linked above hints that there is another flag you can pass, called something like "force-in-process" that should allow libtest to select the InProcess strategy despite you setting panic=abort.

So in case you need to to set panic=abort to get the code coverage working, I would look into setting that flag :)

**Comment by Geigerkind** [comment]
I have tried using this flag together with the panic=abort flag. But it did not work with it. 
I did not debug this any further.

The coverage report looks fine though. I did not notice any significant difference.
