### ISSUE TITLE
Hello from github.com/testcontainers!

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-rs#19]
Hello! I'm Richard; I created the initial Java version of Testcontainers, and I'm very happy to see the idea taking off in Rust as well 😃.

We were wondering if you'd like to join us over on the Testcontainers [Slack team](https://slack.testcontainers.org) to chat and to see if we can help out in any way. We're very hands-off when it comes to language forks, but we want to be supportive and friendly!

Please say hi (myself, @bsideup and @kiview), either on Slack or indeed email/any other channel if you prefer.

**Comment by thomaseizinger** [comment]
I guess we can close this then :)
