### ISSUE TITLE
Usage examples in rustdoc

### ISSUE THREAD

**Issue by TheButlah** [testcontainers/testcontainers-rs#198]
Would it be possible to provide a minimal usage example directly in the rustdocs? Hints on how to get started are provided, but having a minimal complete example would go a long way (new user here).

**Comment by thomaseizinger** [comment]
I guess we could have rustdoc examples that are tagged with `norun` to avoid spinning up too many containers during testing.

Generally, we try to have integration tests for every important features so checking out the [tests](https://github.com/testcontainers/testcontainers-rs/tree/dev/tests) might also help with getting started :)

I can see how that is not super obvious though so we should probably add docs that say that AND provide some rustdoc examples :)
