### ISSUE TITLE
Possible sporadic dynamodb_local_create_table test failure

### ISSUE THREAD

**Issue by ywalterh** [testcontainers/testcontainers-rs#215]
When running `cargo test` on my Linux box, I'm getting this test failure:

```
failures:

---- dynamodb_local_create_table stdout ----
thread 'dynamodb_local_create_table' panicked at '
	expected: result[ok]
	 but was: result[error]<HttpDispatch(HttpDispatchError { message: "Error during dispatch: connection error: Connection reset by peer (os error 104)" })>
', /home/walterh/.cargo/registry/src/github.com-1ecc6299db9ec823/spectral-0.6.0/src/lib.rs:343:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    dynamodb_local_create_table
```

Not sure if this shows up on CI or not. If I'm the only person getting this, feel free to close it.

**Comment by thomaseizinger** [comment]
I think we have had this several times yes. Maybe try updating your dynamodb image with `docker pull dynamodb`. IIRC, we are depending on the `latest` here tag because that is what mimics what is running on AWS.

**Comment by ywalterh** [comment]
I got passed it by running the test a few times and it doesn't happen anymore, if latest is a requirement then we should probably close this issue then.

**Comment by thomaseizinger** [comment]
Yeah, not sure if we can do something about it if we can't reproduce it reliably :/
