### ISSUE TITLE
Move functionality for port overrides to from `Image` to `RunArgs`

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#219]
At the moment, each `Image` implementation has to provide a separate implementation for specifying port mappings: https://github.com/testcontainers/testcontainers-rs/blob/0eb3114e3a5d06955124906c62ee01b7b9fbf8e4/src/core/image.rs#L91

This is not ideal because it creates duplicated code between all images.

We should move this functionality to `RunArgs`: https://github.com/testcontainers/testcontainers-rs/blob/3d80acb27677a5897a5a07a8d5276024a8979d93/src/core/docker.rs#L22

**Comment by dlemel8** [comment]
Hey @thomaseizinger , I want to do this.
Thanks.
