### ISSUE TITLE
Travis CI is unexpectedly failing

### ISSUE THREAD

**Issue by devcdcc** [testcontainers/testcontainers-rs#230]
Hi, i´ve sent a PR #229  but it does not have completed.
This is the message 

> "No output has been received in the last 10m0s".

but it works in local, also I've saw the error in those PRs #221   #228

**Comment by thomaseizinger** [comment]
Hi, thank you for the report!

I am aware of the issue and was hoping that it is just a transient error on travis' side. I don't see anything we could do on our end to fix this.

Worst case we would just have to migrate to GitHub actions and ditch Travis altogether :)

**Comment by thomaseizinger** [comment]
This is up for grabs if anyone is keen on introducing a CI workflow based on GitHub actions.

**Comment by thomaseizinger** [comment]
The transient error seems to be gone now.
