### ISSUE TITLE
Allow to pass string args to docker run

### ISSUE THREAD

**Issue by kunerd** [testcontainers/testcontainers-rs#233]
While trying to start a container with the `--init` option I noticed that it is currently not possible to pass other args then `network` and `name`, or did I miss something?

**Comment by thomaseizinger** [comment]
Yes, that is on purpose. The interface is designed to hide that you are actually talking to the CLI to make things like `https://github.com/testcontainers/testcontainers-rs/pull/216` easier.

This library is also not designed to be a full-fledged docker client but will always be opinionated towards making it easy to write tests.

What is your usecase for needing `--init`?

**Comment by kunerd** [comment]
I'm trying to write containerized test for a dyn-dns server I'm currently working on. I tried to start it in a container for testing, but as of the moment it doesn't handle OS signals very well. I fixed it by adding `tini` directly to its container. I'm new to the concept of `testcontainers`, but I totally understand the design decision to hide the CLI.
