### ISSUE TITLE
Change `KEEP_CONTAINERS=true` to `TESTCONTAINERS=<command>`

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#235]
Given that env variables are accessible to all processes, it feels like we should be using a name for this env variable that creates a "scope" for our program and have the "command" be the variables value.

Currently, we have the following behaviour:

- `KEEP_CONTAINERS=true`: stop all containers but delete all networks that we created. This causes problems as described in #224.
- `KEEP_CONTAINERS=false`: delete all containers and networks

Using an env variable like `TESTCONTAINERS=<command>` makes it clear that we are controlling the behaviour of the `testcontainers` library. It also gives us the opportunity to provide more fine-grained control over what we want testcontainers to do which should allow us to solve #224.

We want to cover the following scenarios:

- Deleting all containers and networks after all tests have been run.
This should be the default so that we don't leave anything behind if the tests execute successfully.
- Stopping all containers after all tests have been run.
This is useful if a test fails and you want to inspect the containers state after the test.

The main tasks of this issue is to come up with good names for these commands.

**Comment by invis87** [comment]
Looks ok for me 👍 
What values `TESTCONTAINERS` command will have? (`clean`, `keep_containers`, `keep_all`) something like this?

**Comment by thomaseizinger** [comment]
>  What values `TESTCONTAINERS` command will have? (`clean`, `keep_containers`, `keep_all`) something like this?

Yes although I think we don't need to support `keep_containers`. Just `keep` is enough. Like you said in #224, keeping around containers but not the networks is not useful :)

Now the question is, should we name the command after:

1. Which command we are sending to the docker daemon, i.e. `stop` vs `remove`.
2. The users intention, i.e. `keep` containers or `remove` them.

Although (1) is more consistent with docker terminology, I think I mildly prefer (2).

Thoughts?

**Comment by invis87** [comment]
Looks  like I don't understand your idea enough.

---
Do you want to get rid from ENV_VAR at all and replace it with some function parameter inside rust code?

If so - I don't like the idea. It is better to be able to change behavior without changing code.

---

Do you want to leave ENV_VAR, but change it behavior?

If so - I agree. But I don't like `KEEP` name - it is too common, also it may collide. 

---

How about `TEST_CONTAINERS` with possible values: `clean` and `keep`. With `clean` ss default value.

**Comment by thomaseizinger** [comment]
Sorry about the confusion!

> If so - I agree. But I don't like `KEEP` name - it is too common, also it may collide.

The idea of this issue is precisely to not have naming collisions and hence rename `KEEP_CONTAINERS` to `TESTCONTAINERS`!

To rephrase, I see the following options (writing out the full example to showcase how it would be used when `cargo test` is run):

1. For not cleaning up any containers / networks after the test run:

a. `TESTCONTAINERS=keep cargo test`
b. `TESTCONTAINERS=stop cargo test` (the idea behind the name `stop` is that this is what we tell the `docker` daemon to do: `stop` the container instead of `removing` it)

2. For cleaning up any containers / networks after the test run: (the intended default behaviour)

a. `TESTCONTAINERS=remove cargo test`
b. `TESTCONTAINERS=clean cargo test`

---

I think I prefer the combination of 1a and 2a.

1b would be more consistent with the underlying command but I think it is too confusing because I expect that in practice, the "remove" / "clean" command is going to be very seldomly used. Hence, the aspired symmetry of `stop` vs `remove` is not going to be as visible and by itself, `stop` doesn't express the intent of "keeping" the containers around as much.

**Comment by invis87** [comment]
> I think I prefer the combination of 1a and 2a.

I agree!

**Comment by thomaseizinger** [comment]
I've implemented this behaviour here: https://github.com/testcontainers/testcontainers-rs/pull/259

While doing that, I had the following thought: Why are we even stopping the container for `TESTCONTAINERS=keep`?

@invis87 What do you think about simply letting them run instead, i.e. not even stop the container?

**Comment by invis87** [comment]
Cool, thanks!

I think keep containers run is "expected behavior" :)

**Comment by thomaseizinger** [comment]
Thanks for confirming!

I changed the implementation to not do anything with the containers in the case of `keep`.
