### ISSUE TITLE
Remodel `Image` trait

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#263]
Get rid of:

- associated type for `Args` by introducing a dedicated string-iterator type that can be constructed from a `vec` and whatever else we need
- associated types for `Volumes` and `Envs` by introducing a dedicated (string, string)-iterator type
- `with_args` function: nothing in the lib uses that
- `with_entrypoint` function: nothing in the lib uses that either
- get rid of `with_args` and `args` by providing dedicated overrides for `Docker::run` where we construct `Args::default` for them or where they can pass their own instance based on the associated type.
- also consider removing fixed `Default` bound and add it to the fn on the `Docker` trait

Make overriding `volumes` and `envs` optional by returning an empty iterator.

**Comment by yottabytt** [comment]
Just to keep you posted, to address this https://github.com/testcontainers/testcontainers-rs/pull/293#discussion_r699712358 neatly, I just started to work on this issue. Hope that's okay? Let's see how far I can get on this.

**Comment by thomaseizinger** [comment]
That would be amazing!

I've been meaning to tackle this forever ...
Please take the issue description with a grain of salt!

The overall goal is to make it as easy as possible to implement a new `Image` while at the same time capturing all the required information to make images work out of the box.

I've pushed some more WIP to https://github.com/testcontainers/testcontainers-rs/pull/269, feel free to inspire yourself or do something completely different :D

**Comment by thomaseizinger** [comment]
Solved excellently by @yottabytt !
