### ISSUE TITLE
Logs of shiplift client don't `follow`

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#271]

**Comment by yottabytt** [comment]
Hey @thomaseizinger , while thinking of TODOs (esp. async support over http client and some hacking around it) for #293 and #294 , I guess I landed upon this bug. IIRC, it ended up at [this error](https://github.com/testcontainers/testcontainers-rs/blob/dev/src/core/logs.rs#L79). In our team at [Etsy](https://en.wikipedia.org/wiki/Etsy), we rely on async a lot whenever possible. It would be great if we get both #293 and #294 with async support. It's also fine to add that support as an immediate follow-up to those PRs (I can also drive that if thats okay). Thoughts?

**Comment by thomaseizinger** [comment]
Yes, chunking things into smaller PRs is totally fine!

**Comment by thomaseizinger** [comment]
Unfortunately, I have little time at the moment to code myself but I'll try to be responsive to anything on here :)

**Comment by yottabytt** [comment]
>I'll try to be responsive to anything on here 

Awesome. That would be really helpful. Thank you :)

**Comment by thomaseizinger** [comment]
Fixed in #323.
