### ISSUE TITLE
Schema registry image

### ISSUE THREAD

**Issue by kakoc** [testcontainers/testcontainers-rs#314]
Hi.
Are there any plans to add schema-registry(https://hub.docker.com/r/confluentinc/cp-schema-registry) for working with Kafka? I think that there are a lot of cases when Kafka is used with SchemaRegistry. So it will help to reproduce such configs for testing.

**Comment by DDtKey** [comment]
Closing as outdated, the testcontainers crate doesn't provide images anymore, it's extracted to separate crate. 
If this is still relevant, please - open an issue there: https://github.com/testcontainers/testcontainers-rs-modules-community/issues
