### ISSUE TITLE
Allow custom docker registry

### ISSUE THREAD

**Issue by mervyn-mccreight** [testcontainers/testcontainers-rs#335]
I think it would be nice to allow some configuration for a custom docker registry to pull the images from.
I'm thinking about a general point of configuration.

This is useful if e.g. you are working in a company that relies on an internal docker repository (e.g. as a caching solution).

**Comment by thomaseizinger** [comment]
Agreed.

I think the best way to extend the current codebase here is to have an optional field in the docker client and produce FQ container names in case they aren't already fully-qualified.

There may also be a config in the CLI that we can use.

**Comment by mervyn-mccreight** [comment]
Cool, I think I'll give it a try 😃

**Comment by DDtKey** [comment]
Actually I might want to use the same client against different registries, moreover the name of images may vary between registries. For example, AWS ECR for docker library would be: `https://gallery.ecr.aws/docker/library/redis`, but not all images from docker-hub are available there and not all of them have the same prefix (e.g bitnami images https://gallery.ecr.aws/bitnami/kafka)

Currently it's enough to set `name` for container to necessary one (e.g`public.ecr.aws/docker/library/redis` or `public.ecr.aws/bitnami/kafka`) 

But we don't expose the way to override the name through `RunnableImage` currently. So I used to re-define images locally with custom `name` for such purposes.

I think the correct way is to allow overriding the name as well as `tag` (already possible) as part of `RunnableImage`. WDYT?

**Comment by thomaseizinger** [comment]
> But we don't expose the way to override the name through `RunnableImage` currently.

Yeah and there is a good reason for that! The `Image` trait is what ties together the image with its version and configuration. That creates a type-safe contract for a working container. Adding the ability to replace the image with a completely different one breaks that contract.

**Comment by DDtKey** [comment]
Yeah, we do allow tag to be overridden and there is a comment that it may broke the image.

What do you think about the second solution? We could allow to change only registry and/or owner in `RunnableImage`. However it's basically the same: changing the registry also may lead to the failure, for example - the image with another hash is kept for the tag

Anyway by redefining the name/registry, I clearly take responsibility on myself.

Btw, looks like it's allowed in other languages: https://java.testcontainers.org/features/image_name_substitution/

**Comment by DDtKey** [comment]
Moreover, nobody prevents us to expose API change the name on `Image` level (like `MyImageX:new().with_name("another")` - testcontainers can't prevent this, people decide what to implement)

But I'd better expose it as part of `RunnableImage`, because in fact, it does broke `Image` itself. We should consider this as a separate customized image.

Even changing of ENV var can break the image and we do allow that, otherwise it would be a mess.

**Comment by DDtKey** [comment]
> That creates a type-safe contract for a working container.

Btw, I think it doesn't work anyway. I encountered a lot of cases when docker tag has been overwritten and broke the existing code which rely on particular tag.
We can't provide any guarantees related to the actual image located by "name" + "tag".

Just for example: https://github.com/bitnami/containers/issues/55274 - image just didn't work for a week or so

**Comment by thomaseizinger** [comment]
Perhaps it is a lost battle :man_shrugging:

**Comment by noelmcloughlin** [comment]
So TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX environment variable is not supported. I did not expect this as works with other languages, so I have been troubleshooting for few hours

**Comment by noelmcloughlin** [comment]
Its increasingly regulatory compliance issue, companies have to proxy external software supply chains, can't use Internet directly

**Comment by noelmcloughlin** [comment]
Thank you, I was looking at ContainerRequest API, but this looks like it might work.
