### ISSUE TITLE
Support multi-document transactions on the MongoDB image

### ISSUE THREAD

**Issue by mervyn-mccreight** [testcontainers/testcontainers-rs#338]
According to the documentation in the [testcontainers-java equivalent](https://www.testcontainers.org/modules/databases/mongodb/) multi-document transactions are only supported for a replica-set.

To support this we need to Initialize a single replica set after container-start up and wait for the completion of the initialization.

This is useful if you want to test code that makes use of transactions, as far as I know it does not work otherwise.

**Comment by thomaseizinger** [comment]
Is it possible to do this via a client - outside of testcontainers - once the container is started?

**Comment by clarkmcc** [comment]
Bumping. Is this theoretically possible for testcontainers to do?

**Comment by mervyn-mccreight** [comment]
As far as I know it should be possible yes. At least using mongosh you can do it.

**Comment by thomaseizinger** [comment]
We will be removing all images from this library, see https://github.com/testcontainers/testcontainers-rs/issues/471.
