### ISSUE TITLE
Support healthcheck customization in docker run

### ISSUE THREAD

**Issue by kezhuw** [testcontainers/testcontainers-rs#342]
Some docker images do not have `HEALTHCHECK`, but they do have commands to verify its health status. Support of healthcheck customization can avoid ad-hoc image.

Given zookeeper(#255) as an example, `./bin/zkServer.sh status` could be used as parameter to `--health-cmd` options in `docker run`.

**Comment by thomaseizinger** [comment]
Closing as a result of closing https://github.com/testcontainers/testcontainers-rs/pull/343.
