### ISSUE TITLE
Questions on encapsullating client creation in struct

### ISSUE THREAD

**Issue by marlon-sousa** [testcontainers/testcontainers-rs#352]
Hello,

I suspect that this is more of a rust knolwedge gap on me, but is ratter something that might happen to others and something, I hope, you can help me to solve.

My problem is simple:

```
use testcontainers::images::postgres::Postgres as PostgresImage;
use testcontainers::{Container, RunnableImage};

use testcontainers::clients::Cli;

pub(crate) type DockerClient = Cli;

pub struct Database<'a> {
    container: Container<'a, PostgresImage>,
    docker_client: DockerClient,
}

impl<'a> Database<'a> {
    pub fn Run(database_name: &str) -> Self {
        let postgres_image = RunnableImage::from(PostgresImage::default())
            .with_tag("13")
            .with_env_var(("POSTGRES_DB", database_name))
            .with_env_var(("POSTGRES_USER", "postgres"))
            .with_env_var(("POSTGRES_PASSWORD", "postgres"))
            .with_mapped_port((5433, 5432));
        let docker_client = DockerClient::default();
        let container = docker_client.run(postgres_image);


        Self {
            container,
            docker_client,
        }
    }
}

```

This does not compile.

My understanding is that it doesn't compile because the run method of the Cli creates a container which has a reference to the Cli itself, so that Cli instance on which the run method was called is required to live as much as the just created container or more.

I understand this. What I don't understand is how to tell the compiler that this is guaranteed to be the case, because the Cli instance and the created container are moved both tto the Database struct, so that both will exist until the Database struct is dropped.

May be the drop order would cause a problem, but then I am out of solutions as how to fix this, because for me it makes sense to encapsulate an container creation with its container.

Thanks,
Marlon

**Comment by thomaseizinger** [comment]
> because for me it makes sense to encapsulate an container creation with its container.

The idea is to not do this :)

If you want to reduce boilerplate, make yourself functions that _build_ images, create the docker client at the top of your function and call your image builder function instead!

We can also rethink whether the whole "attach lifetime of client to container struct" was a good idea but I wouldn't want to rush that decision!

**Comment by thomaseizinger** [comment]
Also curious why you need to set all those env vars? The postgres image should not need any additional parameters for it to work. That is sort of the point of `testcontainers`: That you don't need to configure this stuff :)

**Comment by marlon-sousa** [comment]
Hello,

As for all the variables, I was just experimenting with runnable images and happened to past that example here on my question, but yeah the postgres image itself solves most part of that problem. I needed to overwrite the databasename on my case though and haven't find an exposed way to do that on postgres image.

As for the lifetimes coupling, I can understand why you coupled the container and client together and think it is a valid reason.

I was just looking for a way of still managing all this together in a private way.


I will post a solution here so that people wanting to do the same (couple client and container creation on a struct). As far as I am concerned, this could be closed. People with the same questions will find their way hopefully by reading the code and explanations. can find it. Then I will explain my use case.

https://users.rust-lang.org/t/save-two-fields-with-reference-cycles-in-a-struct/73821/2

```
use ouroboros::self_referencing;
use testcontainers::{clients::Cli, images::postgres::Postgres, Container, RunnableImage};

pub type DockerClient = Cli;

#[self_referencing]
pub struct Database {
    docker_client: DockerClient,
    #[borrows(docker_client)]
    #[covariant]
    container: Container<'this, Postgres>,
}

impl Database {
    pub fn run() -> Self {
        let postgres_image = RunnableImage::from(Postgres::default())
            .with_tag("13")
            .with_env_var(("POSTGRES_DB", "test_database"))
            .with_env_var(("POSTGRES_USER", "postgres"))
            .with_env_var(("POSTGRES_PASSWORD", "postgres"))
            .with_mapped_port((5433, 5432));

        DatabaseBuilder {
            docker_client: DockerClient::default(),
            container_builder: |docker_client| docker_client.run(postgres_image),
        }
        .build()
    }

    // Example method.
    pub fn container(&self) -> &Container<Postgres> {
        self.borrow_container()
    }
}
```

A quick note though: this solution works perfectly. It was not mine, to see the original author follow the above link.

## Use case

I am using testContainers to provide infrastructure for integration on a network of microservices written in rust. Despites the fact that they are several services on a mono repo, integration test means that these services shall not depend on any other service on their tests.

Because these services all are written in rust and share the same repository, I found myself having lots of repeated code on their tests infrastructure, specially by having to use test
Containers (and others), creating containers, initializing database information *** on the containers *** and so on.

Also because of the repeated code, compilation became slower (and this is a very known issue for those who work with rust *** not to blame rust, it has its reasons to be that way ...).

## Solution

To overcome repeated code and compilation speed and also reduce coupling, we decided to create a crate with common test infrastructure in a separate directory. It, therefore:

* reduces repeated code, because container creation and other stuff not related to testContainers can be placed at one place and parameterized.
* Enhances compilation time because the crate compilation can be cached.
* decouple our projects from the testing infrastructure, because we can change for example the ORM or the container orchestrator or any other thing and just run the tests.

But now we have an issue: we cannot delegate to the projects the docker client creation, because doing so means that they would have to include testContainers on their dependencies. Ideally, a project should be able to ask for a database instance and get back a nice connection string, ready for use on their tests.
What we need is a nice encapsulated box which would take care of running a database instance. And this is why I need to manage in a private struct the client and container creation.

**Comment by thomaseizinger** [comment]
Thanks for posting your solution!

I just want to add that encapsulating in a _struct_ may not be the best idea. Structs are for data layout (they are not objects!)

To encapsulate functionality, use functions instead.

You could for example, encapsulate all setup functionality in a function that takes the client as an argument:

```rust
fn setup<'a>(cli: &'Cli) -> Containers<'a> {}

struct Containers<'a> {
    postgres: Container<'a>,
    other: Container<'a>
}
```

**Comment by yatesco** [comment]
(came here to ask this *exact* question - thanks both)
