### ISSUE TITLE
Add a singal handler to clean up test containers when tests are killed

### ISSUE THREAD

**Issue by Licenser** [testcontainers/testcontainers-rs#364]
Right now when a test run is cancled (CTRL-C, kill, etc) for whatever reason the containers are left dangling and require manual cleanup or will be hogging resources on the system.

In 0.12 we solved this by adding a signal handler to remove the containers something like this:

```
b(crate) struct SignalHandler {
    signal_handle: Handle,
    handle_task: Option<JoinHandle<()>>,
}

impl SignalHandler {
    pub(crate) fn new(container_id: String) -> Result<Self> {
        let mut signals = Signals::new(&[SIGTERM, SIGINT, SIGQUIT])?;
        let signal_handle = signals.handle();
        let handle_task = async_std::task::spawn(async move {
            let signal_docker = clients::Cli::default();
            while let Some(signal) = signals.next().await {
                signal_docker.stop(container_id.as_str());
                signal_docker.rm(container_id.as_str());
                let _ = signal_hook::low_level::emulate_default_handler(signal);
            }
        });
        Ok(Self {
            signal_handle,
            handle_task: Some(handle_task),
        })
    }
}
impl Drop for SignalHandler {
    fn drop(&mut self) {
        self.signal_handle.close();
        if let Some(s) = self.handle_task.take() {
            async_std::task::block_on(s.cancel());
        }
    }
}
```

The 0.13 API changes make this impossible since the `stop` and `rm` methods are now bound to a container so they can't be passed into a task for later cleanup.

This functionality seems to be something generally useful so it'd be lovely to have it as part of the framework itself, perhaps behind a feature flag that keeps a global registry of containers started by the framework and just uses one signal handler to close them all on shutdown?

This seems especially useful since rust does not guarantee Drop to be executed.

**Comment by thomaseizinger** [comment]
Hmm, interesting!

I'd like to not re-expose the functions on the `Docker` trait to keep the public API as small as possible.

One general question: The above code seems to rely on `Drop` for `SignalHandler` to be called. How can you guarantee that happens but the `Drop` of a `Container` is not executed?

I guess some form of graceful shutdown would indeed be good, however it is unclear to me how we can provide it in an easy to use way. I am happy to support this within testcontainers if we can find a nice way of fitting it in.

If we can't fit it in a nice way, I am tempted to say it is out of scope. Killing / CTRL+C-ing tests is fairly uncommon and cleaning up dangling containers is a shell oneliner (`docker rm -f $(docker ps -aq)`), hence the added convenience is marginal at best and not worth additional complexity in the API / usage of the library.

Looking forward to proposals in how we can do this!

**Comment by thomaseizinger** [comment]
> Not sure if it's the desired solution but an option aside of extending the public API would be spawning a handler with two channels in an extra thread that's just responsible to clean up during CTRL+C/Kill, it'd remain invisible for the user and a channel::send will not make a significant performance impact compared to whatever `docker start` is already doing. That would keep the API clean and improve cleanup at least for some cases.

Yeah I am happy to add this in such a way!

**Comment by Licenser** [comment]
I'll PR it so you've no extra work?
