### ISSUE TITLE
Container::get_host_port() and IP addresses

### ISSUE THREAD

**Issue by divergentdave** [testcontainers/testcontainers-rs#365]
I ran into an issue recently when trying to connect to a container's mapped port. The root cause was that Docker may assign different host port numbers for a published port on the host's IPv4 and IPv6 addresses. If I used "localhost" with a port number returned from `get_host_port()` I would sometimes get connections to the wrong container, due to mixing and matching an IPv6 address with a port number from Docker's IPv4 port binding. I see that `impl From<bollard_stubs::models::PortMap> for Ports` takes the first port binding from the list it receives from Docker.

To resolve this issue, I think that `get_host_port()` should either make a guarantee that it will return a port number bound on 0.0.0.0, or a breaking change should be made so it either takes an IP address (or choice of IPv4/IPv6) as an argument, or returns one along with the port number.

**Comment by thomaseizinger** [comment]
Thanks for the report! We should indeed return something here that is consistent.

I am not opposed to breaking changes if they make the API better. Would the following fix the issue?

1. Change the current `get_host_port` to always look for the IPv4 mapping.
2. Deprecate the current `get_host_port`
3. Add two new functions: `get_host_port_ipv4` and `get_host_port_ipv6`

**Comment by divergentdave** [comment]
Yes, that sounds good to me!
