### ISSUE TITLE
Lack of a way to pass arguments to generic image

### ISSUE THREAD

**Issue by otavio** [testcontainers/testcontainers-rs#369]
Since `with_args` has been removed we cannot use generic image with arguments.

**Comment by thomaseizinger** [comment]
It was removed because it caused duplicate code in every image definition.

The replacement is to construct a RunnableImage from a tuple of the image and its args: https://github.com/testcontainers/testcontainers-rs/blob/dev/testcontainers/src/core/image.rs#L260-L273

Hope that works for you!
