### ISSUE TITLE
'failed to start container' debug options

### ISSUE THREAD

**Issue by lcmgh** [testcontainers/testcontainers-rs#370]
How can I debug this error? Is there a way to get the output from the actual command call.

`thread 'client::tests::mytest' panicked at 'failed to start container', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/testcontainers-0.13.0/src/clients/cli.rs:48:9`

I'm on a remote dev env. with Vscode SSH-Remote and rust-analyzer. When clicking "run tests" my Docker container fails to start. When I run the test manually with `RUST_LOG=DEBUG cargo test mytest` the container starts properly.

**Comment by thomaseizinger** [comment]
Is the docker daemon running on the remote machine?

**Comment by lcmgh** [comment]
Yes. I should be more precise. 

When I run the test manually **on the remote machine** with `RUST_LOG=DEBUG cargo test mytest` the container starts properly.
