### ISSUE TITLE
New testcontainers-rs release?

### ISSUE THREAD

**Issue by lukehsiao** [testcontainers/testcontainers-rs#373]
There have been several value features merged into testcontainers-rs since v0.13.0. Could we get a release soon so that those using these features can pin to a released version?

**Comment by thomaseizinger** [comment]
> It looks like all the changes were made for the release, but it has not yet been published to crates.io. Is that planned?

That should have happened automatically! Let me check.

**Comment by lukehsiao** [comment]
There it is! Thanks again @thomaseizinger, super excited for this release!
