### ISSUE TITLE
MSSQL with prisma/tiberius example repo

### ISSUE THREAD

**Issue by yatesco** [testcontainers/testcontainers-rs#377]
Hi all, I found it quite tricky to piece together the moving parts to enable MSSQL integration tests. I've figured it out, thanks to various comments in here, and created a working repo at https://github.com/yatesco/rust-mssql-integration-tests

It would have helped me enormously if I could have found this sort of repo in the beginning - would you object if I added it to the README? Or, by all means, copy the code into here as an example, whatever :-). I just want to help others get up and running with this, as this question was a *key* decider when considering "can I move from the JVM to Rust full time".

Thanks!

**Comment by thomaseizinger** [comment]
Thank you!

Looking at the repository, most of this code seems to be around how to connect to an MSSQL server which I'd consider to be a bit too specific as a general "getting started" example.

You are welcome to contribute the image itself back though!

I am also aware that the overall [documentation](https://docs.rs/testcontainers/latest/testcontainers/) could be improved. The bit about multiple crates is outdated for example 😅

The docs.rs frontpage is how people usually get started with a library in the Rust ecosystem. If you've got ideas on how to improve that, please don't hesitate to send a PR! It is difficult to know as a maintainer, what information newcomers are looking for 😊

**Comment by thomaseizinger** [comment]
The current README points to our set of integration tests: https://github.com/testcontainers/testcontainers-rs/tree/dev/testcontainers%2Ftests

Did you find those useful? If not, how could we make that better?

**Comment by yatesco** [comment]
hi @thomaseizinger - you've got it exactly right - it is the assembly of the different things that had value, which is slightly out of scope :-). I find the docs on most crates is very specific, and that's fine and expected, but it is sometimes hard to know how to cobble things together, which is what I was trying to demonstrate. I'll leave this issue here and close it, and that at least will help others googling ;-).

**Comment by yatesco** [comment]
When I get some downtime I'll put together a more focussed MSSQL integration test and send a PR

**Comment by thomaseizinger** [comment]
> hi @thomaseizinger - you've got it exactly right - it is the assembly of the different things that had value, which is slightly out of scope :-). I find the docs on most crates is very specific, and that's fine and expected, but it is sometimes hard to know how to cobble things together, which is what I was trying to demonstrate. I'll leave this issue here and close it, and that at least will help others googling ;-).

Yes. Out of the [four documentation types](https://documentation.divio.com/), docs.rs is mostly a _reference_ and typically weak on the _tutorial_ front.

If you are keen, I think it shouldn't be too hard to add a module that is primary a tutorial but doesn't add any source code as such.
