### ISSUE TITLE
Container and Cli are no longer "Send"

### ISSUE THREAD

**Issue by jhershberg** [testcontainers/testcontainers-rs#381]
We have been working with v0.12.0 and the newer releases have substantial refactors. One that affects us is that we can no longer hold global statics for spawned Containers since the Container object no longer impls Send. Was this a conscious decision and does it really need to be that way. We would like to use your latest release but were not expecting to need to refactor our own test infra.

**Comment by thomaseizinger** [comment]
See also #378.

I think the `Send` issue can be fixed but generally, containers are meant to be per test and not be stored in globals. As mentioned in #378, sharing containers between tests is not a design goal and we are unlikely to support it well, sorry.

The code footprint of testcontainers is quite small. You may want to consider dropping the dependency and writing your own, docker-based test infra if you have very specific requirements.

I'll accept a PR that fixes the particular `Send` issue. I think it can be done with a `+ Send` on the `Docker` trait object held inside.
