### ISSUE TITLE
RunnableImage "fluent" API consumes self

### ISSUE THREAD

**Issue by jhershberg** [testcontainers/testcontainers-rs#382]
The RunnableImage "fluent" API consumes self which works just fine if you have a single chain of calls. However, if you have any variance in how you build your RunnableImage, the API can only be used with significant acrobatics. For example, here I need to keep assigning runnable_image to a new variable:
```
        let runnable_image = match &self.name {
            None => runnable_image,
            Some(name) => runnable_image.with_container_name(name),
        };

        let runnable_image = match &self.network {
            None => runnable_image,
            Some(net) => runnable_image.with_network(net),
        };
```

A worse example is when I want to add a list of ports. The only way I could find to do this such that we can call  with_mapped_port a variable number of times and retain the runnable image object was to use this recursive function:

```
fn add_ports<I: Image>(img: RunnableImage<I>, ports: &mut Vec<u16>) -> RunnableImage<I> {
    match &ports.pop() {
        None => img,
        Some(port) => add_ports(img.with_mapped_port((*port, *port)), ports),
    }
}

...

let runnable_image = add_ports(runnable_image, &mut x);
```

Was there a reason that the with_* APIs could not have accepted a &mut?

**Comment by thomaseizinger** [comment]
The API of testcontainers is generally optimised to not yield code that is meant to be reused but to be so concise that it can easily be duplicated in every test.

This yields better test isolation which is the primary goal of testcontainers.

I don't know your usecase but my generic suggestion would be to not write generic testcontainers code. Either inline it all into your test or have several functions but each without branching.

I'll happily accept PRs that optimise the APIs towards these goals.

**Comment by thomaseizinger** [comment]
Closing as resolved. Please let me know if you have any more questions.
