### ISSUE TITLE
Container re-use? 

### ISSUE THREAD

**Issue by aig787** [testcontainers/testcontainers-rs#391]
It looks like in the newest version `Container::new(..)` has been made `pub(crate)`. To cut down on the cost of spinning up a container per test (some containers I use take a very long time to start) I've been intentionally leaking the containers re-using them on subsequent test runs or spinning up new ones if they don't exist similar to the following

```rust
let container = match container_exists("dynamo") {
            Some(id) => Container::new(id, cli, GenericImage::new("amazon/dynamodb-local")),
            None => cli.run_with_args(
                GenericImage::new("amazon/dynamodb-local"),
                RunArgs::default().with_name("dynamo"),
            )
}
```

Is there a more "blessed" way of doing this now without manually creating my own container object? And if there isn't a better way I'd be happy to PR to either change the visibility or integrate something similar into the workflow better.

**Comment by thomaseizinger** [comment]
Please see #386 and issues linked to that.

**Comment by thomaseizinger** [comment]
I am gonna close this in favor of the redesign issue. This has been brought up a few times, please search the issue tracker for the specific answers :)

**Comment by aig787** [comment]
Didn't realize this use case was covered in the API rework, must have missed it in my searching. I'll take a look, thanks!

**Comment by thomaseizinger** [comment]
> Didn't realize this use case was covered in the API rework, must have missed it in my searching. I'll take a look, thanks!

No worries! There is no ETA on delivering it because I'd like to first collect feedback on it and I need to find some free time to actually implement it :)

**Comment by sillen102** [comment]
> It looks like in the newest version `Container::new(..)` has been made `pub(crate)`. To cut down on the cost of spinning up a container per test (some containers I use take a very long time to start) I've been intentionally leaking the containers re-using them on subsequent test runs or spinning up new ones if they don't exist similar to the following
> 
> ```rust
> let container = match container_exists("dynamo") {
>             Some(id) => Container::new(id, cli, GenericImage::new("amazon/dynamodb-local")),
>             None => cli.run_with_args(
>                 GenericImage::new("amazon/dynamodb-local"),
>                 RunArgs::default().with_name("dynamo"),
>             )
> }
> ```
> 
> Is there a more "blessed" way of doing this now without manually creating my own container object? And if there isn't a better way I'd be happy to PR to either change the visibility or integrate something similar into the workflow better.

How is your ```container_exists``` function implemented?
