### ISSUE TITLE
Ports shouldn't be cached

### ISSUE THREAD

**Issue by schrieveslaach** [testcontainers/testcontainers-rs#392]
Since commit [`88e18b44`](https://github.com/testcontainers/testcontainers-rs/commit/88e18b44d9a6b783e06a66a89819f2dee696e291#diff-51fffd26ca8ee51cf68736432e6066a4d4609544e7675e07eda499c38a10f1ddR66) ports will be cached. However, ports can actually change if a container is assigned to a new network.

You can reproduce this issue by checking out [this commit](https://github.com/aixigo/PREvant/commit/fbdb4615974a1808ea0e5741a57b048a5f588e73) of the [aixigo/PREvant](https://github.com/aixigo/PREvant) respository and you can run `cargo test nginx --manifest-path api-tests/Cargo.toml -- --test-threads=1`.

During the test the traefic container will be connected to the network of an nginx container. This can cause that exposed port mapping will change.

To workaround this issue I have to map the port explicitly:

```rust
let traefik = docker.run(RunnableImage::from(Traefik::default()).with_mapped_port((9789, 80)));
```

**Comment by schrieveslaach** [comment]
Workaround is included in https://github.com/aixigo/PREvant/pull/104. Search for comments mentioning the workaround. You can remove it to reproduce.

**Comment by thomaseizinger** [comment]
Thanks for opening an issue!

I don't recall whether this on purpose or just an oversight. @yottabytt can you add something to this?
I think it should be fine to change this back to fetch the ports on demand. For `ContainerAsync`, we actually still do this.

**Comment by schrieveslaach** [comment]
Thanks for fixing. Works with https://github.com/aixigo/PREvant/commit/22cc416b49939b74f5212bbe580f2da7ecb313db
