### ISSUE TITLE
Allow setting shared memory size

### ISSUE THREAD

**Issue by pbillaut** [testcontainers/testcontainers-rs#395]
Allow users to set the shared memory size (`--shm-size=N`) when creating a runnable container image.

An example for a container where this is useful would be [solace/solace-pubsub-standard](https://hub.docker.com/r/solace/solace-pubsub-standard), which requires at least 1GB of shared memory to be able to run (see [Solace Docs > Resource Requirements for Container Images](https://docs.solace.com/Software-Broker/System-Resource-Requirements.htm#res-req-container)). By default, the `docker run` command sets the shared memory size to 64MB (see [option `--shm-size`](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources)).

Analog feature in testcontainers for Java: https://github.com/testcontainers/testcontainers-java/issues/952.

**Comment by thomaseizinger** [comment]
Sounds reasonable to me, thank you for creating a PR!
