### ISSUE TITLE
Try docker or try podman

### ISSUE THREAD

**Issue by matthiasbeyer** [testcontainers/testcontainers-rs#415]
Hi!

Would be nice to have a `Cli` interface to "try" docker and then podman (or the other way round):

```rust
Cli::try_docker().or_else(|| Cli::try_podman()).unwrap()
```

Would that be possible?

**Comment by thomaseizinger** [comment]
Thanks for opening the issue!

We will be removing support for podman in the near future. See https://github.com/testcontainers/testcontainers-rs/issues/422.
