### ISSUE TITLE
An Entrypoint of "" causes an unwrap to panic

### ISSUE THREAD

**Issue by TheNeikos** [testcontainers/testcontainers-rs#416]
I am using podman, and when running testcontainers-rs with my own image I get this panic:

```
thread 'echoserver' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"\", expected a sequence", line: 146, column: 31)', /bla/bla/testcontainers-0.14.0/src/clients/cli.rs:331:88
```

Looking through the source, it seems that it comes from a serde call not working.

The input that causes this has `"Entrypoint": ""` on the offending line, which when looking at [`bollard_stubs`](https://docs.rs/bollard-stubs/latest/src/bollard_stubs/models.rs.html#502) cannot be parsed. Although the comment is exactly specifying this situation, the code is wrong.

I know it is not part of your library then, but since you are depending on it, I feel like this is the first place it should be reported.

**Comment by TheNeikos** [comment]
This seems to go deeper, as incompatibilities between docker/podman: https://github.com/fussybeaver/bollard/issues/238

I don't think that this can truly be resolved by this project. However I do think that in this case `podman` should not be a 'supported' platform.

**Comment by thomaseizinger** [comment]
Thanks for opening the issue!

We will be removing support for podman in the near future: https://github.com/testcontainers/testcontainers-rs/issues/422.
