### ISSUE TITLE
`bollard-stubs` requirement out of date

### ISSUE THREAD

**Issue by vlad-ivanov-name** [testcontainers/testcontainers-rs#448]
Because `bollard-stubs` is currently pinned at `rc3`, it prevents adding `bollard` to project as it's also pinning it but to `rc7`. My best guess is that the stubs crate is not intended to be depended upon

**Comment by HofmeisterAn** [comment]
Can you elaborate that? The released bollard v0.13.0 pins bollard-stubs v1.42.0-rc.3 too. What version do you use?
