### ISSUE TITLE
Remove all images from the library

### ISSUE THREAD

**Issue by thomaseizinger** [testcontainers/testcontainers-rs#471]
Based on https://github.com/testcontainers/testcontainers-rs/blob/dev/DESIGN_PRINCIPLES.md#ease-of-use, we are removing all existing images from the library.

For one, users tend to not own the images they are contributing, see https://github.com/testcontainers/testcontainers-rs/issues/255, thus placing a big maintenance burden on us.

Two, we want the library to be easy to use such that it is almost not worth bundling them up. Additionally, as we reach a stable API, users can create their own crates for images if they want to.

**Comment by plaflamme** [comment]
Completely understandable from a maintenance perspective.

From an "ease-of-use" perspective, there's an argument to be made that having these ready-made images greatly simplifies the amount of work that a developer needs to do to "get going". A well-designed test image isn't always simple to create, so having a central place to share these would be great and would arguably make it easier to use the library.

Would it be reasonable to consider something like `testcontainers-rs-contrib`? It could allow the community to share images while allowing a different level of support than for `testcontainers-rs` itself from the maintainers. Having a repo-per-image seems like a high maintenance bar for anyone; bundling them up in a single repository would help in that regard.

**Comment by gurinderu** [comment]
Probably it is better to split it into a few crates and describe a dependency list for each crate.
I suggest a such structure
root
|-- Cargo.toml
|-- crates
     |---- core
             |-- Cargo.toml
     |---- kafka
             |-- Cargo.toml
     ....

**Comment by plaflamme** [comment]
Personally, I'd be more inclined to use cargo features instead. At least, I'd start with that before breaking things up into many crates; seems simpler to manage packaging / releasing that way?

**Comment by thomaseizinger** [comment]
As said above, I am more than happy to link to one or more of these crates from the README. Somebody just needs to step up and create a repo :)

We are very permissibly licensed already but you are free to copy all the code verbatim if you want!

**Comment by gurinderu** [comment]
Guys, I made another pr with another crate https://github.com/testcontainers/testcontainers-rs/pull/476

**Comment by DDtKey** [comment]
@gurinderu I believe that @thomaseizinger meant that it shouldn't be as part of this repo & team. Because of responsibility, but it's fine to create community-library with all images

**Comment by gurinderu** [comment]
@DDtKey this library is also community-driven ) I don't see any visible profits to make it in the separate repo, moreover, it will bring more pain

**Comment by thomaseizinger** [comment]
> @DDtKey this library is also community-driven ) I don't see any visible profits to make it in the separate repo, moreover, it will bring more pain

The benefit of making it a separate repo is that it **I** no longer need to maintain these images! Which really is most of the maintenance work at the moment.

Most recent changes to the library were an effort to harden the public API, reducing the potential breaking changes in the future drastically. As such, splitting out another crate & repository isn't much of a pain really.

I am more than happy to onboard new maintainers to the core library but trust obviously has to be earned first before I can grant write-access.

We have a slack channel if you are interested: `#testcontainers-rust` in https://slack.testcontainers.org/.

**Comment by kiview** [comment]
From the overall Testcontainers project vision, we can understand such a move for the current state of the Rust implementation. While different Testcontainers language implementations generally support technology specific pre-configured `modules` (which is the term we try to establish), it requires a concentrated effort to create the architecture to support this is a clean way and publish them potentially as separate artefacts. In addition, the scope of features such a module should provide is currently open for discussion.

I think also for Rust, the state of support for modules is something we might revisit in the future, if circumstances are different. We just recently added full-fledged support for modules in Go and .NET, but this required a very concentrated effort. And also for Java, we have a couple of very good modules, that are maintained by the community in separate repositories, without any bigger issues. 

We can also discuss this more in Slack, as @thomaseizinger mentioned, happy to join the discussion there as well 👍

**Comment by thomaseizinger** [comment]
Thanks for chiming in Kevin!

To give some more context to everyone: I would very much like to have excellent and well-tested modules for testcontainers-rs. It is one of the things we started with when we created this library over 4 years ago. I've since moved on from this job so I am maintaining it in my spare time, which is limited.

I already struggle to find time reviewing PR targeting the core library. Needing to deal with a dozen of dependabot PRs and requests / fixes for images only makes this maintenance work appear so big that I often don't even want to get started on working through the notifications which is why things end up being stale for months.

Removing all images from this repository is therefore a step towards actually improving the maintenance state of testcontainers-rs!

**Comment by thomaseizinger** [comment]
The code of the images is not lost, it is all in Git and I already granted explicit permission to copy it verbatim if desired.

Thanks to everyone who contributed to this discussion.

As I said, I am happy to link to other repositories from the README so don't hesitate to open a PR for that! 😊

**Comment by plaflamme** [comment]
Is hosting this repo under the `testcontainers` org something you would consider?

**Comment by thomaseizinger** [comment]
> Is hosting this repo under the `testcontainers` org something you would consider?

I am only a contributor to the org, not an admin so I don't see myself in the position to make that call but why would that be necessary in the first place? If anything, that suggests some level of support for new users which is what at least I want to move away from.

Does that make sense?

Who actually owns that repository and will do the maintenance work if it sits under the testcontainers org?

**Comment by plaflamme** [comment]
> why would that be necessary in the first place?

It's certainly not necessary, but it would provide a more cohesive story for end-users: they'll just see that it was moved to some other repo under the same org and can more or less trust it's the same thing they used before. Helps discoverability as well.

> Who actually "owns" that repository then and will do the maintenance work if it sits under the testcontainers org?

Presumably the same person that would create a repo in a different GH org? I'm by no means suggesting that any testcontainers people be involved (except initially to set things up I guess).

It's not a big deal, but I think it would be better for end users to have everything be under the same roof. It helps build trust and create a more cohesive ecosystem.

**Comment by thomaseizinger** [comment]
As I said, I am not an org admin but my approach would be to move an _established_ repository under the org and not create a blank one here.

@kiview What do you think?

**Comment by kiview** [comment]
I think it is fine to create such a repository under the Testcontainers GH org, I propose the name `testcontainers-rs-modules-community`. I would like to chose the name `modules` here, since this is what we start to align on as the domain languages across our different language implementations.

I also support @thomaseizinger in the reasons he layed out for moving it into a separate repo rather than increasing the maintenance burden of the existing repo (which is independent from the fact whether we publish it as dedicated artefacts). 

However, we need folks from the community that would be willing to step up in maintaining this community repo, which means taking care of the CI, aligning with new releases of `tc-rust`, reviewing PRs, doing releases, etc. . Who would be willing to take this over?

Alternatively, the approach suggested by @thomaseizinger works as well, we can always move the repository into the org at a later time as well.

**Comment by oleg-nenashev** [comment]
IMHO the contributing guide still needs to be updated after this change https://github.com/testcontainers/testcontainers-rs/issues/487
