### ISSUE TITLE
The Contributing guide does not reflect images removal

### ISSUE THREAD

**Issue by oleg-nenashev** [testcontainers/testcontainers-rs#487]
After the images were removed in https://github.com/testcontainers/testcontainers-rs/pull/473, the CONTRIBUTING guide, which starts from the info about adding images, got obsolete. Now it contains a dead link and no guidelines about what to do with hosting images. I assume one has to create a standalone Crate and self-host it somewhere

**Comment by thomaseizinger** [comment]
Ah yes, thanks for spotting it and sorry for the delay. Happy to take a PR.

**Comment by thomaseizinger** [comment]
There is now https://github.com/testcontainers/testcontainers-rs-modules-community!

**Comment by mervyn-mccreight** [comment]
I'll open a PR to mention the modules project in the docs.

**Comment by mervyn-mccreight** [comment]
I think this is done by now and the issue can be closed.
