### ISSUE TITLE
Can not run docker image with custom args

### ISSUE THREAD

**Issue by loic-j** [testcontainers/testcontainers-rs#494]
I need to pass custom args to the entry point of my docker image and I saw that in v0.13, the args function has been removed from the Image trait:
https://github.com/testcontainers/testcontainers-rs/commit/b5854130ea1f30225c10908617291453ca0c583a#diff-bbaf8e61b2d9cf779e5f8ba8cb900b8d4a79f10ca23660d37ca29635c1a2e686L49

And for what I saw, now containers always run with the default Args implementation:
https://github.com/testcontainers/testcontainers-rs/commit/b5854130ea1f30225c10908617291453ca0c583a#diff-bbaf8e61b2d9cf779e5f8ba8cb900b8d4a79f10ca23660d37ca29635c1a2e686R203
https://github.com/testcontainers/testcontainers-rs/commit/b5854130ea1f30225c10908617291453ca0c583a#diff-86b05d9b72c9c4dd7641ae192b6cfa3978ca8e792151aba097c37695fd90c59bR28

I think we should be able to set custom values for image args. Maybe I am missing something, but I feel that this is an issue introduced in v0.13. Should we revive the args function, or maybe we can add a function to Docker Cli run_with_args ?

**Comment by thomaseizinger** [comment]
As far as this library is concerned, you are essentially running a different image if you need to run it with different args. You should implement the `Image` trait yourself then (or make the args configurable to the point where all your usecase are met by one implementation).

**Comment by RossRogers** [comment]
For folks who need to set the default args, a way to accomplish this could look like:

```
#[derive(Debug, Clone)]
pub struct MyArgs(Vec<String>);
impl Default for MyArgs {
    fn default() -> MyArgs {
        MyArgs(vec![
            "arg1".into(),
            "arg2".into()
        ])
    }
}

impl ImageArgs for MyArgs {
   fn into_iterator(self) -> Box<dyn Iterator<Item = String>> {
       let args = self.0;
       Box::new(args.into_iter())
   }
}

pub struct Foo {}

impl Image for Foo {
    type Args = MyArgs;
    [...]
```
