### ISSUE TITLE
parallel tests hang with multiple instances of rabbit as GenericImage

### ISSUE THREAD

**Issue by alekspickle** [testcontainers/testcontainers-rs#504]
Hey! thanks for the crate, it's fairly useful, but I have a problem with rabbit containers acting up.

I use lapin::Channel in two tests and when I run them they pretty stably hang up and unresponsive
```

test rabbitmq_default has been running for over 60 seconds
test rabbitmq_works has been running for over 60 seconds


```

Although I can see the rabbit containers actually running and can `docker exec ... bash` to them.

```

36ad9b242037   rabbitmq:3.9   "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes   0.0.0.0:33040->4369/tcp, :::33040->4369/tcp, 0.0.0.0:33039->5671/tcp, :::33039->5671/tcp, 0.0.0.0:33038->5672/tcp, :::33038->5672/tcp, 0.0.0.0:33037->15691/tcp, :::33037->15691/tcp, 0.0.0.0:33036->15692/tcp, :::33036->15692/tcp, 0.0.0.0:33035->25672/tcp, :::33035->25672/tcp   agitated_sammet
f5716bdfe059   rabbitmq:3.9   "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes   0.0.0.0:33034->4369/tcp, :::33034->4369/tcp, 0.0.0.0:33033->5671/tcp, :::33033->5671/tcp, 0.0.0.0:33032->5672/tcp, :::33032->5672/tcp, 0.0.0.0:33031->15691/tcp, :::33031->15691/tcp, 0.0.0.0:33030->15692/tcp, :::33030->15692/tcp, 0.0.0.0:33029->25672/tcp, :::33029->25672/tcp   inspiring_rosalind


```

I use my wrapper of course that includes rabbit, redis and uses GenericImage to handle everything the same way, but it does not mess with networking.

**Comment by thomaseizinger** [comment]
The particular images have been moved to https://github.com/testcontainers/testcontainers-rs-modules-community. Please report issues about them there.
