### ISSUE TITLE
[Question] How to specify a newer image for Postgres

### ISSUE THREAD

**Issue by dadepo** [testcontainers/testcontainers-rs#512]
Currently running on the latest version of [testcontainers-rs](https://github.com/testcontainers/testcontainers-rs) which is `0.14.0` and I am running with the [Postgres image](https://docs.rs/testcontainers/latest/testcontainers/images/postgres/struct.Postgres.html)

The only problem is, the version is "11-alpine". How do I use a most recent version of Postgres? I could not easily see how from the documentation.

**Comment by dadepo** [comment]
Using `GenericImage` to construct the image. Then whatever version that is needed can be specified.

**Comment by thomaseizinger** [comment]
> How do I use a most recent version of Postgres? I could not easily see how from the documentation.

This is on purpose. Testcontainer images are design to aid testing and for tests, it is important that they are reproducible. Thus, we don't allow configuration of the version because future versions of postgres might be incompatible with some of the options that are defined in code.
