### ISSUE TITLE
Supports running image with `--user` option.

### ISSUE THREAD

**Issue by liurenjie1024** [testcontainers/testcontainers-rs#517]
It would be quite useful to add `--user` option to run contaniner.

**Comment by thomaseizinger** [comment]
Can you elaborate on your usecase and how it helps when using docker containers for testing? I am hesitant to add additional configuration options.

**Comment by liurenjie1024** [comment]
> Can you elaborate on your usecase and how it helps when using docker containers for testing? I am hesitant to add additional configuration options.

Yeah, for example when I start a container that needs to do some initial setup in entry point script(downloading jars, modify some configuration), it may require another user account for write permission. Starting container with `--user` makes things easier.

**Comment by thomaseizinger** [comment]
> > Can you elaborate on your usecase and how it helps when using docker containers for testing? I am hesitant to add additional configuration options.
> 
> Yeah, for example when I start a container that needs to do some initial setup in entry point script(downloading jars, modify some configuration), it may require another user account for write permission. Starting container with `--user` makes things easier.

Not sure I follow, would the container have a volume mounted or why is the user important? This library primarily focuses on integration testing by booting up databases etc. Its containers _should_ be ephemeral without any persistent state.

Also, to have test run reasonably fast, I'd recommend that you use containers that have all its state already initialized.

**Comment by liurenjie1024** [comment]
> Not sure I follow, would the container have a volume mounted or why is the user important? This library primarily focuses on integration testing by booting up databases etc. Its containers should be ephemeral without any persistent state.

No, it's not a mounted volume.

> Also, to have test run reasonably fast, I'd recommend that you use containers that have all its state already initialized.

Yes, but allowing user to download jars first would make development easier. The actual case is spark sql, which allows user to specify dependencies version and it will automacitally download it from maven central. We can download it, but allowing spark itself to download would make development easier since we can user official spark image.

**Comment by thomaseizinger** [comment]
> > Not sure I follow, would the container have a volume mounted or why is the user important? This library primarily focuses on integration testing by booting up databases etc. Its containers should be ephemeral without any persistent state.
> 
> No, it's not a mounted volume.
> 
> > Also, to have test run reasonably fast, I'd recommend that you use containers that have all its state already initialized.
> 
> Yes, but allowing user to download jars first would make development easier. The actual case is spark sql, which allows user to specify dependencies version and it will automacitally download it from maven central. We can download it, but allowing spark itself to download would make development easier since we can user official spark image.

And why does this need to happen with a certain user?

**Comment by liurenjie1024** [comment]
> And why does this need to happen with a certain user?

When running spark image, by default it's running with `spark` account. When we want to download jars from maven central, it  will store it in `/home/spark/.ivy/repositories`. But by default `/home/spark` is not created, and `spark` account has no permission to create dir in `/home`, this case it requires `root` account to do it.

**Comment by liurenjie1024** [comment]
> That sounds like something that should be fixed in the spark image by e.g. providing a home directory for that user.

That's true. But with this option, the developer doesn't need to maintain another docker image.

**Comment by thomaseizinger** [comment]
> > That sounds like something that should be fixed in the spark image by e.g. providing a home directory for that user.
> 
> That's true. But with this option, the developer doesn't need to maintain another docker image.

I was talking about the upstream spark image! In any case, I am hesitant to add features with an API surface that only serve as workarounds for other problems.

One of the goals of testcontainers-rs is to remain simple with a small API. It is not a generic docker client. I hope you understand.
