### ISSUE TITLE
Stop containers when tests are killed

### ISSUE THREAD

**Issue by mahor1221** [testcontainers/testcontainers-rs#537]
It seems that sometimes containers are not stopped when tests are killed.

Related issue: https://github.com/testcontainers/testcontainers-rs/issues/364

`docker -v`: Docker version 24.0.7, build afdd53b4e3
`rustc --version`: 1.74.0 (79e9716c9 2023-11-13) (Arch Linux rust 1:1.74.0-1)
`testcontainers`: 0.15.0
`testcontainers-modules`: 0.1.3

<details>
  <summary>Minimal reproducible example:</summary>
  
  
```rust
#[cfg(test)]
mod test {
    use testcontainers::{Container, RunnableImage};
    use testcontainers_modules::{postgres::Postgres, testcontainers::clients::Cli};

    fn get_new_pg_container(docker: &Cli) -> Container<'_, Postgres> {
        let pg = Postgres::default();
        let image = RunnableImage::from(pg).with_tag("12-alpine");
        docker.run(image)
    }

    #[test]
    fn test1() {
        let docker = Cli::default();
        let _ = get_new_pg_container(&docker);
    }

    #[test]
    fn test2() {
        let docker = Cli::default();
        let _ = get_new_pg_container(&docker);
    }

    #[test]
    fn test3() {
        let docker = Cli::default();
        let _ = get_new_pg_container(&docker);
    }

    #[test]
    fn test4() {
        let docker = Cli::default();
        let _ = get_new_pg_container(&docker);
    }

    #[test]
    fn test5() {
        let docker = Cli::default();
        let _ = get_new_pg_container(&docker);
    }

    #[test]
    fn test6() {
        let docker = Cli::default();
        let _ = get_new_pg_container(&docker);
    }

    #[test]
    fn test7() {
        let docker = Cli::default();
        let _ = get_new_pg_container(&docker);
    }
}
```

</details>

https://github.com/testcontainers/testcontainers-rs/assets/73415437/1fedc6d1-000c-495f-9ba3-5cace8d7b1bc

**Comment by thomaseizinger** [comment]
We rely on the `Drop` impl in Rust to kill/stop containers. There is no guarantee that this one executes as far as I know, it is on a best effort basis.

There is little we can do about this I am afraid.

I am open to design ideas in making it better. Until then, I am gonna close this as "wont fix".
