### ISSUE TITLE
How to reuse containers within a test run like in Java

### ISSUE THREAD

**Issue by anaether** [testcontainers/testcontainers-rs#548]
Hello, 
Is it currently possible to use/configure the standard Postgres container with the reuse feature as in the Java version for a complete test run? I use actix-web with the testing framework of actix-web-test. I would be very happy about possible ideas/solutions/answers.

**Comment by thomaseizinger** [comment]
As long as you don't drop the container, it can be reused. We don't support declaring global containers yet, see https://github.com/testcontainers/testcontainers-rs/issues/386 for details.
