### ISSUE TITLE
Support overriding "command" for Image

### ISSUE THREAD

**Issue by Warchant** [testcontainers/testcontainers-rs#554]
Current Image supports overriding `entrypoint`, and `env_vars`. I also need to override `command`. 

Use-case is - I want to run multiple instances of the same server (on different ports), each will have `--name={1,2,3}` additional flag. 

With current `type Args;` implementation I can only hardcode a single "default" `command`, but cannot dynamically append new args directly in the test.

**Comment by jorgehermo9** [comment]
It is true that the `RunnableImage` struct does not have a `with_args` method, but it is possible to create a `RunnableImage` with other than the default args.

For example, given `MyCustomImage` struct that implements the trait `Image<Args=Vec<String>>`, you can create a `RunnableImage` with custom args this way: `(MyCustomImage,vec!["first-arg","second-arg"]).into::<RunnableImage>()` 

See [this](https://github.com/testcontainers/testcontainers-rs/blob/71bbdec013c1b19e5507217d52c612c71d9473f5/testcontainers/src/core/image.rs#L325)

**Comment by Tockra** [comment]
> It is true that the `RunnableImage` struct does not have a `with_args` method, but it is possible to create a `RunnableImage` with other than the default args.
> 
> For example, given `MyCustomImage` struct that implements the trait `Image<Args=Vec<String>>`, you can create a `RunnableImage` with custom args this way: `(MyCustomImage,vec!["first-arg","second-arg"]).into::<RunnableImage>()`
> 
> See [this](https://github.com/testcontainers/testcontainers-rs/blob/71bbdec013c1b19e5507217d52c612c71d9473f5/testcontainers/src/core/image.rs#L325)
> 
> Although this, you are right that it would be useful that the `RunnableImage` has a `with_args` method. I've submit a PR addressing this #558.

I ran into the same issue. Now I want to convert a GenericImage (Runnable image) to a image containing the args. But I'm struggling.
Does somebody has a hint?:
```rust
fn get_mongodb_image() -> RunnableImage<GenericImage> {
    let mongo_image = RunnableImage::from(GenericImage::new("mongo", "7.0.7")).with_volume((
        "./tests/db-setup/mongo-init.js",
        "/docker-entrypoint-initdb.d/mongo-init.js",
    ));

    let runable_image = (
        mongo_image,
        vec![
            "mongod",
            "--replSet",
            "rs0",
            "--bind_ip",
            "localhost,127.0.0.1",
        ],
    )
        .into();

    runable_image
}
```
