### ISSUE TITLE
How to get container host ip?

### ISSUE THREAD

**Issue by Warchant** [testcontainers/testcontainers-rs#559]
Testcontainers Java has this `String ipAddress = container.getHost();` method to get container's host IP address. How to do the same with `testcontainers-rs`?

**Comment by DDtKey** [comment]
I think you're looking for  [get_host_port_ipv4](https://docs.rs/testcontainers/0.15.0/testcontainers/core/struct.Container.html#method.get_host_port_ipv4)

**Comment by Warchant** [comment]
> I think you're looking for [get_host_port_ipv4](https://docs.rs/testcontainers/0.15.0/testcontainers/core/struct.Container.html#method.get_host_port_ipv4)

That returns a **port**, not an IP.

**Comment by DDtKey** [comment]
Oh, got it, sorry. Currently it's possible to get IP within bridge network with [get_bridge_ip_address](https://docs.rs/testcontainers/0.15.0/testcontainers/core/struct.Container.html#method.get_bridge_ip_address)
