### ISSUE TITLE
Mapped ports are not updated after container restart

### ISSUE THREAD

**Issue by stormshield-gt** [testcontainers/testcontainers-rs#561]
Since https://github.com/testcontainers/testcontainers-rs/pull/184 we can restart a container. But if we have mapped ports, the value returned by `get_host_port_ipv4(8080)` is not updated.

The current workaround I found is the following, but it's not ideal:

```rust
 let host_port = vault.get_host_port_ipv4(8080) + 1;
```

**Comment by DDtKey** [comment]
Gonna be solved with #392
