### ISSUE TITLE
Hyperlinks in the documentation are broken.

### ISSUE THREAD

**Issue by your-diary** [testcontainers/testcontainers-rs#564]
Hyperlinks in [the official documentation](https://docs.rs/testcontainers/latest/testcontainers/) are broken.

Here's *an* example (the top page): 

![2024-04-04_14_35_16](https://github.com/testcontainers/testcontainers-rs/assets/58146437/48fd1bc0-1e3b-4483-801b-316ef2f8c255)

↓

![2024-04-04_14_35_25](https://github.com/testcontainers/testcontainers-rs/assets/58146437/eb960a47-cf36-43ab-9c47-d250efe02908)

**Comment by DDtKey** [comment]
Thank you for reporting!

This will be fixed in the next release. We actively work on project revamping
