### ISSUE TITLE
Define environment variables

### ISSUE THREAD

**Issue by ufoscout** [testcontainers/testcontainers-rs#57]
How can I define environment variables when starting an image?

Many images can be customized through env vars, for example, Postgres permits to define user, password db name, db init arguments and so on:
```bash
> docker run -e POSTGRES_PASSWORD=mysecretpassword -d postgres
```

For what I see in the Cli ([here](https://github.com/testcontainers/testcontainers-rs/blob/cc8fdbe1645c2d13c6eb74be600e4198316f1b63/cli_client/src/cli.rs#L80)) this is not possible with the current implementation.

**Comment by thomaseizinger** [comment]
Yes this is currently not possible. (As you might notice, `testcontainers-rs` is still in an early stage :smile: )

I think similar to the arguments of an image, one could add a type to the image that defines, which environment variables it accepts:

https://github.com/testcontainers/testcontainers-rs/blob/cc8fdbe1645c2d13c6eb74be600e4198316f1b63/core/src/image.rs#L17-L27

This would allow for a type-safe way to correctly pass the environment variables down to docker.

**Comment by ufoscout** [comment]
I think that the definition of new env vars should not be part of the image but of the CLI.
This exactly how it works on Docker, 

I image it something like:
```rust
    let image = ...;

    // env vars on the CLI startup definition
    let cli = clients::Cli::default().withEnv("USER", my_user).withEnv("PASSWORD", my_pass);

    let node = docker.run(image);
```

If you agree I could prepare a PR

**Comment by thomaseizinger** [comment]
The env vars are only useful though if the image also picks them up.
In fact, in "traditional" command line docker, env vars belong to containers, i.e. running images. I'd say those correspond to Image *instances* in `testcontainers-rs`.

I think it would provide a huge benefit if an `Image` defines the possible env vars (as linked above) and upon instantiation, you can pass in an instance of those.

This would make sure you cannot misspell the env variables.

Even if we don't put the types on the image, I don't think they should go on the `Docker` instance. What if you start multiple different images with it? Then env vars would be set that are not picked up by the image.

**Comment by D4nte** [comment]
Pre-defining env var for each image removes a lot of flexibility. I think it should be up to the user to define and pass them.

**Comment by thomaseizinger** [comment]
> I think that the definition of new env vars should not be part of the image but of the CLI.

They should be part of the `run` API somehow but not the instance of the `Cli`.

Possible ways:
- builder API returned from a method like `build_run`
- extend list of arguments of `run`

**Comment by ufoscout** [comment]
@thomaseizinger @D4nte 

Following the [testcontainers Java approach](https://www.testcontainers.org/features/creating_container/), they could be specified directly in the image:

```rust
    let image = MyImage{}.withEnv("USER", my_user).withEnv("PASSWORD", my_pass);
```

What do you think?

**Comment by thomaseizinger** [comment]
> Following the testcontainers Java approach, they could be specified directly in the image:

That was my original approach :)
With the associated type on the image, you can have a method `with_env(self, Self::Env) -> Self`.
Self::Env be any type (also a HashMap) but it would probably be nice if we provide a simple Wrapper around HashMap that allows you to define arbitrary env variables.

For an image like `postgres`, we could then define a type like:
```rust
struct PostgresEnv {
    username: String,
    password: String
}
```
