### ISSUE TITLE
[Feature request]: add capabiltities support

### ISSUE THREAD

**Issue by stormshield-gt** [testcontainers/testcontainers-rs#578]
It would be great to have [capabilities](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) support.
My current use case is for the` hashicorp/vault` image that require the  `IPC_LOCK` capability

**Comment by nicmr** [comment]
@DDtKey I've started implementing this, shouldn't be too different from #724 , but this time for `cap_add` and `cap_drop`

**Comment by nicmr** [comment]
@DDtKey @stormshield-gt can we close this since #726 was merged?

**Comment by DDtKey** [comment]
Sure, thank you for implementing this! 🙏
