### ISSUE TITLE
Support for volume mounts

### ISSUE THREAD

**Issue by jonathanmorley** [testcontainers/testcontainers-rs#61]
Some images will depend on files in the repo, we should have a way to reference them within the image, by allowing mountpoints into the container

**Comment by thomaseizinger** [comment]
Given we also have #57, I think it is time to define a 2nd method on `Docker` that returns some builder trait to specify all this stuff on.

Something like:

```rust
docker.build_run(image)
    .with_env(...)
    .with_mount(...)
    .run()

```
