### ISSUE TITLE
How to wait for container to finish running? 

### ISSUE THREAD

**Issue by KShivendu** [testcontainers/testcontainers-rs#676]
I want to wait for my container to exit naturally with exit code = 0. How can I achieve this?

**Comment by DDtKey** [comment]
Hi!
Could you elaborate on this? What's the case?
The container performs some work and you want it to finish before proceeding with your flow?

Currently there is no such wait strategy in Rust implementation at least, but we can consider the support of this.

**Comment by KShivendu** [comment]
> want it to finish before proceeding with your flow?

Yes

> but we can consider the support of this

Would be great. I think Golang already has [this](https://golang.testcontainers.org/features/wait/exit/).

**Comment by DDtKey** [comment]
[ExitWaitStrategy](https://docs.rs/testcontainers/0.20.0/testcontainers/core/wait/struct.ExitWaitStrategy.html) has been implemented and released in `0.20.0` 🚀
