### ISSUE TITLE
Specify host port of exposed port.

### ISSUE THREAD

**Issue by VladasZ** [testcontainers/testcontainers-rs#697]
If I understand correctly currently `expose_ports` method of `Image` trait allows users to specify only container port. For host port it automatically assigns some temporary port starting from 55000. 
But how do I specify both container and host ports like I do it in `docker` cli with `-p 5432:5432` argument?

**Comment by DDtKey** [comment]
Hi @VladasZ 👋 

You're looking for [mapped port](https://docs.rs/testcontainers/latest/testcontainers/core/trait.ImageExt.html#tymethod.with_mapped_port)

**Comment by DDtKey** [comment]
Additionally, depending on your use case, you may not need port mapping.

Instead, you can get the host port used for a specific exposed port using
[get_host_port_ipv4](https://docs.rs/testcontainers/latest/testcontainers/core/struct.ContainerAsync.html#method.get_host_port_ipv4) of already started container

**Comment by VladasZ** [comment]
Hi @DDtKey Yeah this is exactly what I was looking for. Thank you very much! 
I understand advantages of mapping containers to different ports and I already used `get_host_port_ipv4` in some of my tests. 
But in other test I needed to map to default `Postgres` port and `with_mapped_port` works perfectly for this.
