### ISSUE TITLE
Support customize CMD for GenericImage

### ISSUE THREAD

**Issue by tisonkun** [testcontainers/testcontainers-rs#701]
I can see that we support customize entrypoint. Is there any blocker from supporting CMD also?

**Comment by DDtKey** [comment]
Hi there 👋 

I think there is no blockers for this, and it's currently supported with [ImageExt::with_cmd](https://docs.rs/testcontainers/latest/testcontainers/core/trait.ImageExt.html#tymethod.with_cmd)
In general, `ImageExt` was introduced to unify the interface and make overrides simpler for any `Image`.

But we can extend `GenericImage` too.
