### ISSUE TITLE
Cutting out a new release

### ISSUE THREAD

**Issue by stormshield-gt** [testcontainers/testcontainers-rs#711]
I will be very interested if you could please cut out a new ~~minor release~~ patch release.
I'm looking into the upgrade of `rustls`  to 0.23 which we just get through https://github.com/testcontainers/testcontainers-rs/pull/710 that update `bollard` to 0.17

**Comment by DDtKey** [comment]
Hi @stormshield-gt 👋 

Not sure I got you.
Do you want us to rollout a new minor release with #710 included?

**Comment by stormshield-gt** [comment]
> I wanted to prepare a major release soon, there are some breaking changes in main.

Did you mean minor release ? Or you are going 1.0.0 ? It any case it will definitely work for me.

> Otherwise we might consider a patch release with only this change, however it's not a fix

Because this crate has not reached 1.0.0 yet, I think it's OK to use patch release for all non-breaking changes. If we use  minor release even for non-breaking changes, it adds a burden to downstream users. 
For instance, 0.20 is not [semVer compatible](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility) with 0.21 so it won't be updated automatically by `cargo update`, and users will have to manually update their *Cargo.toml* files.
`rustls` for instance use patch release for non-breaking changes.

**Comment by DDtKey** [comment]
By major I meant minor part of semver. 
Just wanted to highlight that there are breaking changes and we use `minor` part for these.

It will be `0.21.0`

**Comment by DDtKey** [comment]
Actually, we can't backport deps update. 
In general, upgrade of `rustls` to `0.23` is breaking change and may affect users - there are some [platform-related limitations in this version](https://aws.github.io/aws-lc-rs/index.html)

**Comment by stormshield-gt** [comment]
Actually, it seems that [bollard wants to force the ring provider ](https://github.com/fussybeaver/bollard/blob/01413b7b0263ab74bd0026582b1a5825b8055504/Cargo.toml#L60) that doesn't have the NASM requirement on windows. 

But I think they didn't disable default features so maybe they are bringing both `ring` and `aws-lc-rs` provider, I will check that and open an issue there. I think they should re-export the provider as features, as did the rest of the ecosystem like [tokio-rustls](https://docs.rs/crate/tokio-rustls/latest/features) or [hyper-rustls](https://docs.rs/crate/hyper-rustls/latest/features).

Besides, as docker is more linux/unix oriented, maybe Windows is not such a concern. The workaround is just to add a dependency on NASM if someone really wants to run test container on windows.

> Btw, what's the issue with having 0.22 & 0.23? They can co-exist.
And testcontainers is usually only dev-dependency. What's the reason of a rush?

No need for rush, I opened the issue to say that they are a need, but I don't want to put any pressure. Sorry if I did.
For me it's just a matter of denying `rustls` 0.22 everywhere, so my coworkers are forced to use the [process default provider](https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#using-the-per-process-default-cryptoprovider), even for not dev dependency. Maybe tools like `cargo deny` can allow a crate only for dev-dependency

**Comment by DDtKey** [comment]
> Actually, it seems that [bollard wants to force the ring provider ](https://github.com/fussybeaver/bollard/blob/01413b7b0263ab74bd0026582b1a5825b8055504/Cargo.toml#L60)that doesn't have the NASM requirement on windows.

> But I think they didn't disable default features so maybe they are bringing both ring and aws-lc-rs provider, I will check that and open an issue there. I think they should re-export the provider as features, as did the rest of the ecosystem like [tokio-rustls](https://docs.rs/crate/tokio-rustls/latest/features) or [hyper-rustls](https://docs.rs/crate/hyper-rustls/latest/features)

Yeah, they don’t disable default ones. And anyway - features are additive. Some another dep may enable it.

> Besides, as docker is more linux/unix oriented, maybe Windows is not such a concern. The workaround is just to add a dependency on NASM if someone really wants to run test container on windows.

I think there is no problem in it. I’m only wanted to highlight that it can’t be considered as “compatible” change unfortunately

**Comment by DDtKey** [comment]
Hi @stormshield-gt 👋 

I've released `0.21.0` version

**Comment by stormshield-gt** [comment]
Hi @DDtKey , thanks a lot! I've done a PR to `bollars` to solve the problem we talk about by the way https://github.com/fussybeaver/bollard/pull/441
