### ISSUE TITLE
[Feature request]: Allow specifiying the working directory

### ISSUE THREAD

**Issue by nicmr** [testcontainers/testcontainers-rs#720]
Equivalent to the docker run `-w, --workdir` flag.
This would be extremely useful for some workloads and allow for feature parity with other testcontainer implementations.
I might try to contribute this myself if I can find the time - I will leave a comment in this thread if I start working on it.

For reference:
- Go implementation has added this feature with https://github.com/testcontainers/testcontainers-go/pull/1899 
- Java implementation added this feature with https://github.com/testcontainers/testcontainers-java/commit/e2b61d45c702af93375c32ff4132d07c84f179d0

**Comment by DDtKey** [comment]
Hi @nicmr 👋

Thank you for the request and references! 🙏

This shouldn’t be a problem to extend [ContainerRequest](https://docs.rs/testcontainers/latest/testcontainers/core/struct.ContainerRequest.html) and [ImageExt](https://docs.rs/testcontainers/latest/testcontainers/core/trait.ImageExt.html)

I will be glad to accept a PR

**Comment by nicmr** [comment]
Hi @DDtKey, thank you for the hints. I've taken a look at the types you linked and `bollard` and I think I have a good idea of how to implement this. I'll try to submit a PR this weekend :)

**Comment by nicmr** [comment]
Closing this one as it was implemented with #724. Thank you for the guidance and the review @DDtKey. Also kudos for having such a clean codebase, it was easy to understand how things work under the hood.
