### ISSUE TITLE
Abrupt shutdown not properly handled

### ISSUE THREAD

**Issue by feelingsonice** [testcontainers/testcontainers-rs#727]
Run a container through this crate and abruptly shut it down with something like ctrl+c, and the containers would still be running. This leaves docker in an invalid state and either have consequences on subsequent runs or leaves a bunch of dangling containers.

Personally for me, a huge pain of testing with docker is state management. If I programmatically spin up docker containers via invoked system commands, I have to manage its state, figure out if it's actually started, free the ports, shut it down etc. This is just all not worth it for me. 

The [cornucopia](https://github.com/cornucopia-rs/cornucopia) crate, for example, uses the postgres docker to validate SQL schemas and generate sql queries at compile time, and it does this via docker containers created via `std::process` commands, and its [auto-build](https://github.com/cornucopia-rs/cornucopia/tree/main/examples/auto_build) feature is literally broken right now because it doesn't fully manage the state of the docker containers it created.

`testcontainers` solves a huge part of this problem for me but I was disappointed to see that it didn't shutdown the containers when w/e program abruptly stopped. It would be really nice if it could at least do a best effort try when this happened :)

**Comment by DDtKey** [comment]
Hi 👋 

Have you tried `watchdog` feature? It's not comprehensive at the moment, but handles signals and stops containers.

But in general it's known issue and will be covered with #577

**Comment by feelingsonice** [comment]
No idea it existed, how do I used it?

**Comment by DDtKey** [comment]
Just enable the feature

**Comment by DDtKey** [comment]
I’m going to close this issue as is known and should be solved by #577 
I hope you don’t mind

**Comment by feelingsonice** [comment]
Hmm interesting, it worked. Curious how this is different from what I have. I thought that `drop` is called for static vars when the program terminates?

**Comment by DDtKey** [comment]
I guess you answered in wrong issue.

No, drop isn't called for static variables. See my answer in the relevant issue and check the conversations in other similar ones
