### ISSUE TITLE
example usage for DOCKER_AUTH_CONFIG

### ISSUE THREAD

**Issue by amab8901** [testcontainers/testcontainers-rs#728]
Hi!

I read in the docs about DOCKER_AUTH_CONFIG being used for authenticating via Docker. Can u give me examples of how this is used?

**Comment by DDtKey** [comment]
Hi @amab8901 👋 

It's generally documented on [our docs site](https://rust.testcontainers.org/features/configuration/#docker-authentication) and [docs.rs too](https://docs.rs/testcontainers/latest/testcontainers/#docker-authentication)


`DOCKER_AUTH_CONFIG` allows to set a json content (just like raw content of `config.json`), while `DOCKER_CONFIG` allows to set path to your custom config file.

Content is like:

```json
{
	"auths": { },
	"credsStore": "..."
}
```

**Comment by amab8901** [comment]
I haven't used config files before. If my username is `user123` and my password is `pass123`, should I write the following as a value to `DOCKER_AUTH_CONFIG`?
```
{
  "auths": { 
    "username": "user123",
    "password": "pass123"
  },
  "credsStore": ""
}
```

**Comment by DDtKey** [comment]
Not really, "auths" represents list of registries and their configs.

You can check the one managed by docker (via `docker login` command). And `testcontainers` uses this one by default.

```sh
cat ~/.docker/config.json
```

* path to config depends on your docker configuration

**Comment by amab8901** [comment]
I don't have username and password stored in docker config, so doing `cat ~/.docker/config.json` doesn't reveal to me where I'm supposed to put the username and password in the docker config

**Comment by DDtKey** [comment]
Usually `CredentialsStore` used and username and passwords are not part of config, see https://docs.docker.com/reference/cli/docker/login/
