### ISSUE TITLE
Using Local Images

### ISSUE THREAD

**Issue by amab8901** [testcontainers/testcontainers-rs#729]
My understanding is that [`GenericImage::new(..)`](https://docs.rs/testcontainers/0.22.0/testcontainers/struct.GenericImage.html#impl-GenericImage) can only pull from external repo, but cannot use images that are already in the local environment like the ones u see in `docker images`. Can u add support for the latter?

**Comment by DDtKey** [comment]
There is no any restrictions for local images. It's supported and moreover we rely on this on our test-suite (we build [test-images](https://github.com/testcontainers/testcontainers-rs/tree/main/testimages)) - [example of such test](https://github.com/testcontainers/testcontainers-rs/blob/df5fb05370a07f681834b1e1785d519230408b92/testcontainers/tests/sync_runner.rs#L155-L159)

Testcontainers just uses HTTP API of Docker and connects to your instance (whether you use local or remote one)
